version: "3.4"
services:
  exchange-rate:
    env_file:
      - .env
    container_name: exchange-rate
    image: exchange-rate-backend:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${DOCKER_TARGET-production}
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "${PORT-7500}:7500"
    depends_on:
      cache:
        condition: service_healthy
  cache:
    image: redis:6.2-alpine
    ports:
      - "${REDIS_PORT-6379}:6379"
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local